name: Deploy

on:
  push:
    branches: [main]

env:
  AWS_REGION: us-east-1
  IMAGE_TAG: ${{ github.run_number }}

jobs:

  build:
    runs-on: ubuntu-latest

    outputs:
      image: ${{ steps.out.outputs.image }}

    steps:
    - uses: actions/checkout@v4

    - name: Configure AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login ECR
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build & Push (VERSIONED ONLY)
      run: |
        IMAGE=${{ vars.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}

        docker build -t $IMAGE .
        docker push $IMAGE

        echo "image=$IMAGE" >> $GITHUB_OUTPUT
      id: out


  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v4

    - name: Configure AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Make scripts executable
      run: chmod +x infra/scripts/*.sh

    - name: Detect slot
      run: bash infra/scripts/detect_slot.sh
      env:
        ALB_LISTENER_ARN: ${{ vars.ALB_LISTENER_ARN }}
        BLUE_TG_ARN: ${{ vars.BLUE_TG_ARN }}
        GREEN_TG_ARN: ${{ vars.GREEN_TG_ARN }}
        BLUE_SERVICE: ${{ vars.BLUE_SERVICE }}
        GREEN_SERVICE: ${{ vars.GREEN_SERVICE }}
        AWS_REGION: ${{ env.AWS_REGION }}

    - name: Register task definition
      run: bash infra/scripts/register_task.sh
      env:
        IMAGE_URI: ${{ needs.build.outputs.image }}

    - name: Deploy ECS
      run: bash infra/scripts/deploy.sh
      env:
        ECS_CLUSTER: ${{ vars.ECS_CLUSTER }}